services:
  - type: web
    name: scheduler-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /health
databases:
  - name: scheduler-db
    plan: free
