services:
  - type: web
    name: scheduler-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build && npm run db:migrate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
  - type: pserv
    name: scheduler-db
    env: postgresql
    plan: free
    region: oregon
